# Generated by Django 4.2 on 2023-06-07 20:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tienda', '0003_rename_nombte_producto_nombre'),
        ('App_Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineaProducto',
            new_name='LineaPedido',
        ),
    ]
