# Generated by Django 4.2 on 2023-06-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pedidos', '0002_rename_lineaproducto_lineapedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
