# Generated by Django 4.2 on 2023-05-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_producto_created_producto_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombte',
            new_name='nombre',
        ),
    ]
